### ISSUE TITLE
Please help 

### ISSUE THREAD

**Issue by KrisSzyp** [VitalySvyatyuk/pocket_option_trading_bot#10]
I have new system.
Install phyton 3.12 on Microsoft store
Instal. NET .6.0 in your link
pip3 install -r requirements.txt
and run 
python3 po_bot.py or
![po_bot](https://github.com/VitalySvyatyuk/pocket_option_trading_bot/assets/173461398/344ab8a4-a3f0-42c2-b7e1-8e5bfb665a9f)
python3 po_bot_indicators.py or
![po_bot_indicators](https://github.com/VitalySvyatyuk/pocket_option_trading_bot/assets/173461398/234d0a04-5f73-4b05-9731-7157a1aee376)
python3 po_bot_ml.py
![po_bot_ml](https://github.com/VitalySvyatyuk/pocket_option_trading_bot/assets/173461398/7d92f3b7-aee9-4f7c-af1d-9f8e0bd58de9)

po_bot work good, po_bot_indicators - 0 reaction, po_bot_ml - erros

What am I doing wrong? I don't know anything about python, but if the first bot works, it means the rest should work too. Please help.
@VitalySvyatyuk

**Comment by KrisSzyp** [comment]
I change not work.

**Comment by KrisSzyp** [comment]
I get MASOS @VitalySvyatyuk 
bot work good
ml have a problem
Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Decimal.Parse(String s)
a indicators work and not get any transactions

**Comment by VitalySvyatyuk** [comment]
@KrisSzyp you can try different version of Python
Or debug your current setup, set breakpoints to find an issue

**Comment by KrisSzyp** [comment]
> @KrisSzyp you can try different version of Python Or debug your current setup, set breakpoints to find an issue
Problem solved macos must be in the package in English, not Polish as in my case. Thanks a lot
