### ISSUE TITLE
chrome driver

### ISSUE THREAD

**Issue by chukwuemekaamblessedchinenye** [VitalySvyatyuk/pocket_option_trading_bot#4]
please how can i set up  the chrome driver i am using chrome version 125.0.6422.142

**Comment by VitalySvyatyuk** [comment]
you can download chromedriver here: https://googlechromelabs.github.io/chrome-for-testing/

**Comment by Leoalv72** [comment]
Hi, I have downloaded the chromedriver in the same directory as the bot, C:\Users\Leo\Downloads\pocket_option_trading_bot-main ... how can I write this path on line 83 and 85 so that the bot work? Thanks

**Comment by Leoalv72** [comment]
> Hi, I have downloaded the chromedriver in the same directory as the bot, C:\Users\Leo\Downloads\pocket_option_trading_bot-main ... how can I write this path on line 83 and 85 so that the bot work? Thanks

I got it, I need to enter the file too.. C:/Users/Leo/Downloads/po_bot/chromedriver.exe
I gonna try to change it to my own strategy .. and Donate you when I get some profit. Thanks so much.

**Comment by chukwuemekaamblessedchinenye** [comment]
help me please

i encounter this error after adding the path
on line 32 

service = Service(executable_path=r'C:\Users\ChukwuemekaAmblessed\Downloads\chromedriver-win64\chromedriver.exe')

PS C:\Users\ChukwuemekaAmblessed\Documents\github project\trading bot\pocket_option_trading_bot-main\pocket_option_trading_bot-main> python po_bot_indicators.py
Opening in existing browser session.
Traceback (most recent call last):
  File "C:\Users\ChukwuemekaAmblessed\Documents\github project\trading bot\pocket_option_trading_bot-main\pocket_option_trading_bot-main\po_bot_indicators.py", line 33, in <module>
    driver = webdriver.Chrome(options=options, service=service)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ChukwuemekaAmblessed\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\ChukwuemekaAmblessed\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\ChukwuemekaAmblessed\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\ChukwuemekaAmblessed\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ChukwuemekaAmblessed\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ChukwuemekaAmblessed\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
        GetHandleVerifier [0x00007FF7CBBC3E42+31618]
        (No symbol) [0x00007FF7CBB3B0A9]
        (No symbol) [0x00007FF7CB9F888A]
        (No symbol) [0x00007FF7CBA30507]
        (No symbol) [0x00007FF7CBA2BC8F]
        (No symbol) [0x00007FF7CBA78864]
        (No symbol) [0x00007FF7CBA77EC0]
        (No symbol) [0x00007FF7CBA6CEB3]
        (No symbol) [0x00007FF7CBA3A46B]
        (No symbol) [0x00007FF7CBA3B001]
        GetHandleVerifier [0x00007FF7CBECA01D+3202397]
        GetHandleVerifier [0x00007FF7CBF16A3D+3516285]
        GetHandleVerifier [0x00007FF7CBF0C4B0+3473904]
        GetHandleVerifier [0x00007FF7CBC75D46+760454]
        (No symbol) [0x00007FF7CBB46B4F]
        (No symbol) [0x00007FF7CBB41CE4]
        (No symbol) [0x00007FF7CBB41E72]
        (No symbol) [0x00007FF7CBB3121F]
        BaseThreadInitThunk [0x00007FFE324B7344+20]
        RtlUserThreadStart [0x00007FFE333626B1+33]

**Comment by chukwuemekaamblessedchinenye** [comment]
do you have a youtube channel

**Comment by VitalySvyatyuk** [comment]
chukwuemekaamblessedchinenye try to pull last version, it might be fixed already

**Comment by Leoalv72** [comment]
Hi, I try to use indicator.py or bot_ml.py but I have an error.. I need to change some text in the Path vars to open the browser in the PO page, like this:
![chromedriver](https://github.com/VitalySvyatyuk/pocket_option_trading_bot/assets/172874464/34cae3fc-4f04-460f-956a-1998c9616caa)

The error show 'list index out of range' for CANDLES, I notice the candles[ ] in 'data' var is empty.. like this:
![image](https://github.com/VitalySvyatyuk/pocket_option_trading_bot/assets/172874464/5d541f39-2d11-4986-8d40-ca6428c36a9e)
I Still try to understand the code too, sorry. 
Any help will be appreciated. Thanks.

**Comment by Leoalv72** [comment]
Opsss.. Sorry, I just hadn't changed the timeframe from 5s to 1M... it's working. Thanks.

**Comment by chukwuemekaamblessedchinenye** [comment]
hello still finding it difficult to setup please help
if possible video tutorial on youtube to set it up and running
thanks in advanced
